### ISSUE TITLE
Gaining speed on wallruns that don't happen.

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#105]
Lately when you use the key combinations for a wallrun while no wall is present, the screen would jostle a little, as if a wallrun had started and instantly stopped.  This does provide speed to the player, and can be abused to go from stationary to the 420 speed cap considerably quickly.

**Comment by ScrewdriverHyena** [comment]
This is currently fixed on the dev version (not one which is currently on the dev server branch)
