### ISSUE TITLE
Wallrun acceptance range bug

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#107]
If you attempt to telewallrun to a new wall from a position that is close to being in line with it, the wallrun will not execute.  The angle this goes to is pretty wide.  The image shows a position that you cannot wallrun from, despite being able to wallrun to the same wall even further away so long as you are further to the right than I am there.
![wallrun_position](https://user-images.githubusercontent.com/55211707/83090956-01796f80-a068-11ea-9cea-34819c949f0a.jpg)

**Comment by ScrewdriverHyena** [comment]
We can't reproduce this. Let us know if it happens again and I'll reopen this issue.
