### ISSUE TITLE
Error sign blocking top half of screen

### ISSUE THREAD

**Issue by Laforeze** [ScrewdriverHyena/ParkourFortress-Bugs#110]
source mod error sign is blocking half the screen in first person

**Comment by flueysucks** [comment]
this is because you have cl_downloadfilter set to mapsonly in console. try setting it to cl_downloadfilter all, and retry. if the problem persists, try deleting the viewmodels entirely in your tf2 directory Team Fortress 2\tf\download\models\parkourfortress and parkoursource

**Comment by ScrewdriverHyena** [comment]
Has this been fixed?
