### ISSUE TITLE
Crouch-rolling pauses/changes music?

### ISSUE THREAD

**Issue by sirattano** [ScrewdriverHyena/ParkourFortress-Bugs#118]
Whenever I crouch-roll, the music either pauses or changes. Not only that, but it interrupts the end-round stalemate sound as well.

**Comment by Magnanix** [comment]
This is known, and while we are looking into method(s) to fix, this was also a known issue with the defunct Slag PF

**Comment by ScrewdriverHyena** [comment]
Closing this as we're not looking for a fix for this issue
