### ISSUE TITLE
Teleport commands reset velocity

### ISSUE THREAD

**Issue by TheRealMrPhil** [ScrewdriverHyena/ParkourFortress-Bugs#119]
Using teleport commands, such as /b or /s, on maps without those areas causes velocity to be reset. This lets you avoid death by fall. 

https://user-images.githubusercontent.com/7016156/117234897-d957cc00-adf3-11eb-813f-9e0284e84cec.mp4

**Comment by ScrewdriverHyena** [comment]
From all I'm aware, this is resolved. Let me know if it's still an issue.
