### ISSUE TITLE
Relay Chat Troubles (Post Europe)

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#120]
- I used sm_crosschat, and the server said that it enabled crosschat, making me believe the default is set to off.
- I couldn't see europe messages on the US server before or after using crosschat
-After enabling it, I did see messages coming from discord, but another player on the server could not while not having used the crosschat command.  So I believe at this point we had opposite crosschat toggle, and still neither of us could see europe's messages.
-Also, the indicator that someone has crosschat disabled [!] appears to be backwards of what it should be, where having [!] on relay currently denotes it being enabled.

**Comment by ScrewdriverHyena** [comment]
@ratlasob Is this still happening?

**Comment by ratlasob** [comment]
I am pretty sure that when relay was worked on it got sorted out, i haven't seen europe messages lately but i think that just has to do with time of day and player count, and im more or less sure the crosschat command works as intended now.
