### ISSUE TITLE
Cannot get onto server (PF_offshore_V8). 

### ISSUE THREAD

**Issue by Jvp2001** [ScrewdriverHyena/ParkourFortress-Bugs#122]
I have deleted the map files and restarted the game, but still not working, sorry if the problem is easy to fix, but it has been a long time since I have played PF. 

![Cannot Join Map Error](https://user-images.githubusercontent.com/14146913/123503851-8230e380-d64d-11eb-9964-f13d69a071ad.png)

**Comment by ManeGunner6** [comment]
Also getting this issue, even when I delete the map files and verify game files I can't load into the EU server whatsoever.
![image](https://user-images.githubusercontent.com/52790824/124108824-6dde5380-da5e-11eb-8758-430b12e1abe3.png)
![image](https://user-images.githubusercontent.com/52790824/124108843-72a30780-da5e-11eb-8285-b9fd622ad057.png)

**Comment by oWave** [comment]
Should be fixed, Let us know if it still happens.
