### ISSUE TITLE
Game breaking bugs. 

### ISSUE THREAD

**Issue by Rezpit** [ScrewdriverHyena/ParkourFortress-Bugs#131]
m no bizaitch to complain, I personally love parkour fortress, but I can't say I haven't found some trouble along the way. Found bugs that need fixing quite bad...

First of all, the map pool is incomplete / some maps are missing, but yet they are counted as incomplete, therefore noone can achieve 100% of finished maps. (the maps in question are dark meat, darker meat, repairkour b9, acrasia b5 acrasia r1, and offshore v9_1)

Second of all, wallrun range is shortened. Usually that'd be a good thing, but considering bonuses for not so nuance are impossible because of this "change", i think the way to fix this is either:
a) Change back the wallrun range (Recommended, takes less time and less effort)
b) Change the maps

Then I found this bug - when you die, while taunting, and you respawn, you die immideatly.

I think last bug I found is, when you rtv for a map, join any team, wait for the "Waiting for players" to run out, slide to gain speed, your speed automatically sets to 0. This happened alot on Sakura, Mandrillmaze, Mizuki and Not so Nuance.

Now I got some... other bugs that've been there since day 1 but not sure if they're intentionally left there.

Wall lunging
Jumping high when climbing a wall and hanging
Trying to wallrun makes you jump off the wall sometimes
Welp, that's it. Incase needed, I can make a video showing the bugs. Add me on Discord - ПΛƬΣ#9157 #

**Comment by ScrewdriverHyena** [comment]
Duplicate of issue on main PF Repo.

**Comment by Serafeline** [comment]
Duplicate. Closing and will work main issue.
