### ISSUE TITLE
Bug with ledge dropping

### ISSUE THREAD

**Issue by SyKohaspooping** [ScrewdriverHyena/ParkourFortress-Bugs#18]
Back in slag spamming crouch on a ledge would let you regrab it which was smt i and probably many others liked since it was forgiving for a misinput. in this mod you can't do that and I think that's because you have a lot of velocity as soon as you drop down which can be fixed by: removing not needing to hold w on a ledge, force falling off a ledge to start with a slower velocity or no velocity and transition to max fall speed.

**Comment by namishere** [comment]
Was a bug on SLAG, its removal here is intentional

**Comment by koopa516** [comment]
I will be looking for community consensus regarding ledge dropping.

**Comment by namishere** [comment]
Could make make the cooldown timer dynamic based on when you last grabbed a ledge, and allow for an unspammable number of regrabs that way.
