### ISSUE TITLE
Quick Getup Inconsistency

### ISSUE THREAD

**Issue by jvizzlezz** [ScrewdriverHyena/ParkourFortress-Bugs#20]
In TF2, as well as most source games, if you are jumping onto a platform of any sort that isn't too high (ie you don't need to crouch in order to get onto it), you can cancel the upwards momentum of jumping up, allowing you to continue running instantly. You can do this by crouching at the right time (depending on the height of the ledge), and, with certain heights, it can be done very consistently with enough practice. For lack of a better term, I'll call it the "quick getup". Old (slag) parkour featured this very well, and with enough effort you could do quick getups on practically any surface so long as you were able to grab onto it. Some exceptions were there, but those almost always involved tight spaces such as in vents (at the end of eversion, etc). In new parkour, while getting up ledges quickly is still possible, it's way more inconsistent than it was before. Shuk suggests that this is because the height value upon grabbing the ledge is variable and therefore hard to predict when to press crouch.

On a related note, slag parkour had a mechanic wherein if a ledge was not _too_ high up, you could run up it instantly without any need to crouch or do anything. Although this also happens in new parkour, I feel as though it is way too tight. Areas that I could do the auto-getup in slag I can no longer do, and it makes some areas of maps where you're expected to them, way slower and clunkier. There are several points in hekto where this is a problem (though not necessarily a bug), but I'm certain that there are more areas like this in other maps too.

**Comment by ScrewdriverHyena** [comment]
Fixed at some point
