### ISSUE TITLE
X/Z axis Issues with Doors

### ISSUE THREAD

**Issue by jvizzlezz** [ScrewdriverHyena/ParkourFortress-Bugs#24]
While, to the best of my knowledge, this was also a bug in slag parkour, I feel like it needs to be said regardless. Rarely, when hitting a door open, you may find yourself slightly off-center with where you were before, likely because of the hitbox of the door itself. Not a heinous issue for most maps, and it's rare enough that it isn't serious regardless, but maps with very tight doorways may be harder to run because of it. Allowing players to hit the door from further away may fix this minor bug.

On a more serious note, many maps have different ways in which a door will open, which can sometimes lead to them being frustrating to run through in a quick manner. This isn't a bug, and is more of an issue on a map-per-map basis, but some notable offenders would include pf_cave and pf_factory_office, and, to some degree, pf_eversion. Probably way more. The fundamental problem is that some doors require you to be more to the left than to the right, and some require you to be more to the right than to the left, or else you'll end up running into the door frame itself once the door is open, or in bad cases, simply not opening the door at all. I believe this could also be fixed, to some degree, by making the hitting of doors more lenient.

**Comment by ScrewdriverHyena** [comment]
We don't really have a way to fix this issue, but should we come across something I will reopen this issue.
