### ISSUE TITLE
show outlines for start/(end?) zones

### ISSUE THREAD

**Issue by itVictor** [ScrewdriverHyena/ParkourFortress-Bugs#27]
(I'm aware some zones might be remade so this might be moot but oh well)

Unlike in bhop/surf maps, zones in pf maps are usually not visually defined, As a result, zones are completely invisible to the player aside from the timer on the screen, this becomes an issue in some maps where it's not obvious where you leave the start zone. This then causes issues if you try to do starting strats like wallrunning/sliding at the beginning of the map, because if the zone outline is invisible, you don't know where to actually start sliding/wallrunning without getting blocked by the timer for exceeding speed/performing certain actions within the start zone.

**Comment by ScrewdriverHyena** [comment]
This most likely won't be happening.
