### ISSUE TITLE
Only add move/keyframe_rope entities marked as ziplines by mapper

### ISSUE THREAD

**Issue by namishere** [ScrewdriverHyena/ParkourFortress-Bugs#36]
Likely accomplished by only accepting pairs with a certain targetname prefix, or by some other data within the entity if this is somehow not accessable

**Comment by koopa516** [comment]
Going to need to discuss this potential change in a broader aspect, regarding how we're going to make PF better for mappers in general.

**Comment by ScrewdriverHyena** [comment]
See #37
