### ISSUE TITLE
Map Start bug.

### ISSUE THREAD

**Issue by AbyssalCrow** [ScrewdriverHyena/ParkourFortress-Bugs#39]
Loaded into PF_Dimensions_S4 and the map start boundary was for some reason extended through the entire starting platform, preventing anybody from wallrunning/climbing to actually continue the map, Tried to see if it was consistent with the specific map but a reload into dimensions shows it fixed itself. Thought i'd bring it up for future reference incase it happens again.
![20190522181911_1](https://user-images.githubusercontent.com/50751414/58213205-49302300-7cbf-11e9-916c-7f24169b6ff1.jpg)

**Comment by ScrewdriverHyena** [comment]
This is caused by a recurring issue with the timer in which zones sometimes don't load properly.

**Comment by ScrewdriverHyena** [comment]
Fixed in commit 37e73d.
