### ISSUE TITLE
Wallrun ending erroneously

### ISSUE THREAD

**Issue by namishere** [ScrewdriverHyena/ParkourFortress-Bugs#46]
At pf_rebound_final,
setang -3.021569 167.502472 0.000000; setpos -3748.343750 -5997.120117 -1598.968750;
This walllrun will cancel because the trace made by function Wallrun misses. I'm not sure what would be a clean fix for this.
![hl2_2iybEbLtPU](https://user-images.githubusercontent.com/50415197/58918440-251d0a80-86df-11e9-9396-4d34810c8ac0.png)

**Comment by flueysucks** [comment]
isn't that a map thing? the wall on the left probably isn't one gigantic clip brush, right???

**Comment by namishere** [comment]
Looking at it, it does appear that I did not put clip brushes here, though i did in other places. Another reason to hate my past self.

**Comment by flueysucks** [comment]
hahaha, i'm not very educated on mapping or coding things so i'm glad i suggested something that was right

**Comment by namishere** [comment]
Fixing the missing clipping at this point would either require a recompile (i don't have source anymore but a decompile will do well enough) or adding in an invisible func_brush on the plugin side. I'm still interested in handling edge cases like this through the plugin, but again, I can't think of any good way to do it.

**Comment by ScrewdriverHyena** [comment]
Closing this for now, should there be any new initiative toward handling wallrun edge cases, feel free to reopen.
