### ISSUE TITLE
Cannot do parkour actions after restarting with "/r"

### ISSUE THREAD

**Issue by car-keys** [ScrewdriverHyena/ParkourFortress-Bugs#49]
Tested on pf_pink. When restarting with "/r", was unable to grab ledges or wallrun. After killing myself (using the kill console command), I was able to do these things again. Happened consistently after testing.

**Comment by namishere** [comment]
I've modified how the plugin applies and removes the locked state, can you confirm whether or not this is fixed?

**Comment by ScrewdriverHyena** [comment]
I have not heard any reports of this in recent times. Closing.
