### ISSUE TITLE
Mizuki wallclimb is broken.

### ISSUE THREAD

**Issue by SkystrikeTF2** [ScrewdriverHyena/ParkourFortress-Bugs#50]
After the rising platforms on the map pf_mizuki, normally you are supposed to climb up a large wall by grabbing onto splits in the wall and utilizing the pillar behind you. For some reason, I could not grab onto these splits, thus making the wallclimb impossible and the map unbeatable.

**Comment by namishere** [comment]
Fixed as of commit 2ce80a6
