### ISSUE TITLE
Mutliple Bugs

### ISSUE THREAD

**Issue by Beezlebard** [ScrewdriverHyena/ParkourFortress-Bugs#52]
Using the commands 
alias +pda "cyoa_pda_open 1";alias -pda "cyoa_pda_open 0"
bind shift "+duck;-pda"
Then crouching gives infinite speed

Jumping at the end of the slide maintains the velocity of the slide shooting you forward.

Hopping sideways with one key in a duct with full speed lets you max 500 u/s instead of 420.

**Comment by ScrewdriverHyena** [comment]
Bug 1 fixed in commit #3cb5c7

Bug 2 will be addressed in #54 

Bug 3 will be addressed in #57
