### ISSUE TITLE
"Slide boosting"

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#54]
If you slide off of any ledge, whether it be the end of a ramp or just an otherwise flat platform that ends, and you time a +jump command within a few particular frames immediately after "leaving" the edge, the horizontal momentum from the slide is maintained, an extra altitude boost is made due to the jump, and an additional double jump is still possible after performing this.

Replicating this is difficult, but it is certainly not just random.

**Comment by ScrewdriverHyena** [comment]
Can anybody confirm whether or not this still happens, and if it does, can I have a demo or video of it?

**Comment by ratlasob** [comment]
Awhile ago when changes were made to sliding generally, doing this became close to impossible, even more than it already was.  Since then I've experienced it only extremely sparingly and with the effect being less potent.  I can try to record it happening but I wouldn't promise results.
