### ISSUE TITLE
Parkour actions requiring +forward

### ISSUE THREAD

**Issue by ratlasob** [ScrewdriverHyena/ParkourFortress-Bugs#59]
You can no longer slide nor longjump without having +forward active.

Sliding used to require any horizontal movement, and could be done with any or no movement command paired with it.

Long jumping could be done with any or no movement command paired with it.  Unlike sliding, longjumping used to require no horizontal movement, and could be done while completely stationary, as long as "speed" was still active.

**Comment by ScrewdriverHyena** [comment]
Fixed in cac1a3 and eb1969.

Slides are now possible in all directions as long as there is horizontal motion in that direction totaling over 200 hu.
