### ISSUE TITLE
Wallclimb prioritizing over wallrun

### ISSUE THREAD

**Issue by shuk-fuk** [ScrewdriverHyena/ParkourFortress-Bugs#67]
https://youtu.be/PS1a3V6cVBg

wallruns should have priority in this situation since you have to hold 2 keys for a wallrun and only 1 key for a wallclimb.

**Comment by Magnanix** [comment]
The system is not intuitive, if you watch your position reported by cl_showpos, you can tell when the system will force you into a wallclimb or wallrun. It's going to be a problem no matter the corner where both are possible.

For Frosty (Screwdriver), add a check in wallclimb to not initiate if strafing has been instructed, this will stop unintentional wallclimbs in this case

**Comment by ScrewdriverHyena** [comment]
This should be fixed in commit e69d01.
