### ISSUE TITLE
voter shouldn't autopick so fast if there's only one person in server

### ISSUE THREAD

**Issue by itVictor** [ScrewdriverHyena/ParkourFortress-Bugs#72]
~~title, !revote doesn't work~~
see below

**Comment by itVictor** [comment]
I was wrong, it does work but if you close the menu while you're the only player in the server it auto chooses, should wait before doing that in case somebody changes their mind

**Comment by ScrewdriverHyena** [comment]
This is native sourcemod functionality, I don't think there's any way for me to change that unless I code a voter from scratch.
