### ISSUE TITLE
add !voteextend (!ve)

### ISSUE THREAD

**Issue by itVictor** [ScrewdriverHyena/ParkourFortress-Bugs#73]
currently there is only one chance to vote per map, after which point several players could leave and you might want to stay on the map rather than going to the next one, hence adding a separate !ve command (functioning in the same way that !rtv works)

I can see not wanting this when there's only one server for pf but I definitely encourage it should pf expand to more servers

**Comment by shuk-fuk** [comment]
this. we need a proper vote extend instead of needing everyone to join spectate to restart the timer.

**Comment by ScrewdriverHyena** [comment]
This was added.
