### ISSUE TITLE
wallrunning problem

### ISSUE THREAD

**Issue by mogoars** [ScrewdriverHyena/ParkourFortress-Bugs#75]
i can't wallrun on left walls for some reason??
it just wont work
right walls work perfectly for me but i cant say the same for left walls

please fix this if you can!

**Comment by Magnanix** [comment]
Hi there! There's not much detail in this report so I'll have to ask a few questions.

Our PF movement is functional, but not without bugs as you might have discovered! There are many contributions to parkour movement errors. To start, please verify through tf2 console that you are indeed holding +Forward and +Left before also imputing +Jump. By this I mean there's no other possible interactions on your bind keys if you've modified from default keybindings.

Next, was the inability to left wallrun an occurance from the start entering the server, or did it become an issue after some time playing? If the latter, do you remember when it occurred?

Lastly, did you try to kill your instance (death and respawn) or disconnecting and re-enter the server?
