### ISSUE TITLE
/tutorial expansion

### ISSUE THREAD

**Issue by Magnanix** [ScrewdriverHyena/ParkourFortress-Bugs#77]
For future use if not currently viable, release /tutorial from a pre-scripted mode and add in overrides of appropriately named triggers (_multiple)

Zones to include are;
-Welcome/Sprint (Might be best to pair these together)
-Sprintjump
-Slide
-Ledge Grab
-Vault
-Climbable
-Wallclimb
-Wallrun
-Wallkick**
-Zipline**
*

Optional;
-Stun*
-Death*
-Crouch 
-Second Jump Disable Threshold

Extra;
There might be a point where custom overlays are wanted to explain other parts, (metas) this could be solved by allowing "customoverlay#"

*Moved
**Added

**Comment by ScrewdriverHyena** [comment]
Progress made: We've got new tutorial graphics for an overhaul, however most of the goals of this post are no longer really being aimed for
