### ISSUE TITLE
Glare on screen

### ISSUE THREAD

**Issue by defenitlynotironicedgyboy** [ScrewdriverHyena/ParkourFortress-Bugs#78]
I keep getting a white glare on parts of the screen at random times while playing sometimes its small and trasparent enough that i barely notice it and other times its so bright i cant see anything on the left side of the screen, it mostly takes the left side of the screen but sometimes the whole screen will have it

**Comment by Magnanix** [comment]
Does this have any similarities to [Issue #71](https://github.com/ScrewdriverHyena/ParkourFortress-Bugs/issues/71)

**Comment by defenitlynotironicedgyboy** [comment]
yeah it is im new to the sence and i did not know there was another report already

**Comment by ScrewdriverHyena** [comment]
Duplicate of #71.
