### ISSUE TITLE
"Out of memory or addressspace. Texture quality setting may be too high." crash after a few minutes of play (or even less)

### ISSUE THREAD

**Issue by festivengy** [ScrewdriverHyena/ParkourFortress-Bugs#80]
I'm still new to the PF-revived servers. But this is an issue I never dealt with on the og servers. When I play for a minute or more I will usually receive a crash. Simply saying "Engine Error." and "Out of memory or address space. Texture quality setting may be too high."

**Comment by itVictor** [comment]
That error is related to an old tf2 bug related to custom sounds, nothing that the mod can fix unfortunately.

To fix the error, browse to your tf folder, search for `.cache` and delete all the files that come up (you will have to do this somewhat regularly).
