### ISSUE TITLE
Update parkour.tf [website] map panel

### ISSUE THREAD

**Issue by Magnanix** [ScrewdriverHyena/ParkourFortress-Bugs#82]
Requesting to modify the Author table to include hyperlinks of their Steam profile using non-changeable uniqueID, this way anyone with access has a mean to directly find the correct author for an update request or notification.

**Comment by LucasNimny** [comment]
Steam IDs are not stored when inputting the author section of map uploads therefor there's not good way to hyperlink the steam profiles without it leading to issues down the line.
