### ISSUE TITLE
Voltage ending doesnt work

### ISSUE THREAD

**Issue by Cuttyflame** [ScrewdriverHyena/ParkourFortress-Bugs#84]
Me and 3 people reached voltage ending today but it wasnt working, the green endzone doesnt stop your time

**Comment by ScrewdriverHyena** [comment]
This is a known issue with the timer where it randomly fails to load a zone. It's being worked on, but very slowly as there's no way to really know when we've fixed it since it happens randomly.

**Comment by ScrewdriverHyena** [comment]
Fixed in commit 37e73d.
